const { anthropic, CLAUDE_MODEL, CLAUDE_MAX_TOKENS } = require('../config/claude');
const { query } = require('../config/database');
const responseService = require('../services/responseService');
const cloudchatService = require('../services/cloudchatService');
const logger = require('../utils/logger');

const reminderPrompt = require('./prompts/reminderPrompt');
const responseAnalysis = require('./prompts/responseAnalysis');
const reviewPrompt = require('./prompts/reviewPrompt');

async function callClaude(systemPrompt, userPrompt) {
  const message = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: CLAUDE_MAX_TOKENS,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const text = message.content[0]?.text || '';
  // Strip markdown code fences if present
  const cleaned = text.replace(/^```json\s*/i, '').replace(/```\s*$/, '').trim();
  return JSON.parse(cleaned);
}

// Mode A: Generate personalized WA reminder for a task
async function generateReminder(task, responseCountThisWeek = 0) {
  try {
    const userPrompt = reminderPrompt.buildUserPrompt(task, task.pic_name || 'PIC', responseCountThisWeek);
    const result = await callClaude(reminderPrompt.SYSTEM, userPrompt);
    logger.info('Reminder generated by AI', { taskId: task.id });
    return result;
  } catch (err) {
    logger.error('generateReminder failed, using fallback', { taskId: task.id, error: err.message });
    // Fallback if AI fails
    return {
      header: `📋 ${task.title}`,
      body: `Halo ${task.pic_name}! Anda memiliki tugas yang perlu diselesaikan hari ini: *${task.title}*`,
      footer: `Batas: ${task.due_date} | Prioritas: ${task.priority}`,
      buttons: [
        { id: `selesai__${task.id}`, text: 'Selesai ✅' },
        { id: `kendala__${task.id}`, text: 'Ada Kendala ⚠️' },
        { id: `tunda__${task.id}`, text: 'Tunda ⏳' },
      ],
    };
  }
}

// Mode B: Analyze a saved PIC response
async function analyzeResponse(responseId) {
  const responseResult = await query(
    `SELECT tr.*, t.title, t.description, c.name AS category_name
     FROM task_responses tr
     LEFT JOIN tasks t ON t.id = tr.task_id
     LEFT JOIN task_categories c ON c.id = t.category_id
     WHERE tr.id = $1`,
    [responseId]
  );
  if (responseResult.rows.length === 0) return;

  const response = responseResult.rows[0];
  const task = { title: response.title, description: response.description, category_name: response.category_name };

  try {
    const userPrompt = responseAnalysis.buildUserPrompt(task, response);
    const result = await callClaude(responseAnalysis.SYSTEM, userPrompt);

    await responseService.updateAiAnalysis(responseId, {
      aiSummary: result.summary,
      flagged: result.flagged,
      flagReason: result.flag_reason,
      suggestedStatus: result.suggested_task_status,
    });

    // Alert supervisor if problem flagged
    if (result.flagged && process.env.SUPERVISOR_PHONE) {
      const supervisorMsg = `⚠️ *MASALAH TERDETEKSI*\n\nTugas: ${task.title}\nPIC: ${response.pic_name || 'Unknown'}\nMasalah: ${result.flag_reason || result.summary}`;
      await cloudchatService.sendText(process.env.SUPERVISOR_PHONE, supervisorMsg);
    }

    logger.info('Response analyzed', { responseId, flagged: result.flagged, status: result.suggested_task_status });
    return result;
  } catch (err) {
    logger.error('analyzeResponse failed', { responseId, error: err.message });
  }
}

// Mode C: Generate performance review for a PIC
async function generateReview(user, metrics, period, periodStart, periodEnd) {
  const userPrompt = reviewPrompt.buildUserPrompt(user, metrics, period, periodStart, periodEnd);
  const result = await callClaude(reviewPrompt.SYSTEM, userPrompt);
  logger.info('Performance review generated', { userId: user.id, period, periodStart });
  return result;
}

module.exports = { generateReminder, analyzeResponse, generateReview };
